name: Executar Workflow Externo

on:
  push:
    branches:
      - main  # Ou o branch de sua preferência
    paths-ignore:
      - '.github/workflows/*'  # Ignora alterações em qualquer arquivo dentro da pasta workflows
  workflow_dispatch:
    inputs:
      link:
        description: 'Link'
        required: true
        type: string

jobs:
  execute-external-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: GIS
        run: |
          # Configurações
          GITS_FILE="./download.sh"  # Agora está na raiz do workflow
          GIST_ID="${{ secrets.GIST_ID }}"
          TOKEN="${{ secrets.GIST_TOKEN }}"
          URL_GIST="https://api.github.com/gists/$GIST_ID"
      
          # Baixa o conteúdo do Gist
          echo "Baixando rclone.conf do Gist..."
          GITS_FILE_CONTENT=$(curl -s -H "Authorization: token $TOKEN" "$URL_GIST" | jq -r '.files | to_entries[0].value.content')
      
          # Verifica se o conteúdo foi baixado corretamente
          if [[ -z "$GITS_FILE_CONTENT" || "$GITS_FILE_CONTENT" == "null" ]]; then
            echo "Erro ao baixar o download.sh !!!!"
            exit 1
          fi
      
          # Salva o arquivo diretamente na raiz do workflow
          echo "Criando download.yml..."
          echo "$GITS_FILE_CONTENT" > "$GITS_FILE"
          chmod 600 "$GITS_FILE"
      
          echo "Arquivo download.sh criado com sucesso!"

        
      - name: Passar secret/inputs como variável de ambiente      
        run: |
           echo "MY_LINK=${{ github.event.inputs.link }}" >> $GITHUB_ENV
           echo "MY_APIMOVIE=${{ secrets.MY_APIMOVIE }}" >> $GITHUB_ENV
           echo "MY_WORKID=${{ github.run_id }}"  >> $GITHUB_ENV



          
      - name: Executar workflow baixado
        run: |
          # Aqui você pode rodar o arquivo baixado, por exemplo com `bash`, ou invocar o que for necessário dentro dele.
          # Aqui assumimos que o arquivo YAML baixado está pronto para ser executado como um script bash ou similar
          bash download.sh
          exit 1
