name: Executar Workflow Externo

on:
  push:
    branches:
      - main  # Ou o branch de sua preferência
    #paths-ignore:
      #- '.github/workflows/*'  # Ignora alterações em qualquer arquivo dentro da pasta workflows

jobs:
  execute-external-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar arquivo de workflow do Gits
        run: |
          URL_GIST="https://api.github.com/gists/c33735ca0b794861000b959304cffe6c"
          GITS_FILE="./download.yml"  # Agora está na raiz do workflow
          GIST_ID="2d1fb527588a1203c624504a1565e8cc"
          URL_GIST="https://api.github.com/gists/$GIST_ID"
          #### Baixa o conteúdo do Gist
          echo "Baixando download.yml do Gist..."
          GIST_CONTENT=$(curl -s -H "Authorization: token $TOKEN" "$URL_GIST" | jq -r '.files | to_entries[0].value.content')
          
          # Verifica se o conteúdo foi baixado corretamente
          if [[ -z "$GIST_CONTENT" || "$GIST_CONTENT" == "null" ]]; then
            echo "Erro ao baixar o download.yml"
            exit 1
          fi
  
          # Salva o arquivo diretamente na raiz do workflow
          echo "Criando download.uml..."
          echo "$GIST_CONTENT" > "$GITS_FILE"
          chmod 600 "$GITS_FILE"  
          echo "Arquivo download.yml criado com sucesso!"
          
          env:
            TOKEN=${{ secrets.GIST_TOKEN }}
        
      - name: Passar secret como variável de ambiente      
        run: |
          export MY_SECRET=${{ secrets.MY_SECRET }}
          echo "Secret passado com sucesso, mas não visível nos logs."

          
      - name: Executar workflow baixado
        run: |
          # Aqui você pode rodar o arquivo baixado, por exemplo com `bash`, ou invocar o que for necessário dentro dele.
          # Aqui assumimos que o arquivo YAML baixado está pronto para ser executado como um script bash ou similar
          #bash external-workflow.yml
          echo "teste"
          exit 1
