name: Executar Workflow Externo

on:
  push:
    branches:
      - main  # Ou o branch de sua preferência
    #paths-ignore:
      #- '.github/workflows/*'  # Ignora alterações em qualquer arquivo dentro da pasta workflows

jobs:
  execute-external-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Rclone Config
        run: |
          # Configurações
          RCLONE_CONF_FILE="./rclone.conf"  # Agora está na raiz do workflow
          GIST_ID="${{ secrets.GIST_ID }}"
          TOKEN="${{ secrets.GIST_TOKEN }}"
          URL_GIST="https://api.github.com/gists/$GIST_ID"
      
          # Baixa o conteúdo do Gist
          echo "Baixando rclone.conf do Gist..."
          RCLONE_CONF_CONTENT=$(curl -s -H "Authorization: token $TOKEN" "$URL_GIST" | jq -r '.files | to_entries[0].value.content')
      
          # Verifica se o conteúdo foi baixado corretamente
          if [[ -z "$RCLONE_CONF_CONTENT" || "$RCLONE_CONF_CONTENT" == "null" ]]; then
            echo "Erro ao baixar o rclone.conf!"
            exit 1
          fi
      
          # Salva o arquivo diretamente na raiz do workflow
          echo "Criando rclone.conf..."
          echo "$RCLONE_CONF_CONTENT" > "$RCLONE_CONF_FILE"
          chmod 600 "$RCLONE_CONF_FILE"
      
          echo "Arquivo rclone.conf criado com sucesso!"

        
      - name: Passar secret como variável de ambiente      
        run: |
          export MY_SECRET=${{ secrets.MY_SECRET }}
          echo "Secret passado com sucesso, mas não visível nos logs."

          
      - name: Executar workflow baixado
        run: |
          # Aqui você pode rodar o arquivo baixado, por exemplo com `bash`, ou invocar o que for necessário dentro dele.
          # Aqui assumimos que o arquivo YAML baixado está pronto para ser executado como um script bash ou similar
          #bash external-workflow.yml
          echo "teste"
          exit 1
